insert into usuario (nombre,email,contraseña) values ("Armando","armando@gmail.com","armando1234");
insert into usuario (nombre,email,contraseña) values ("Miguel","miguel@gmail.com","miguel1234");
insert into usuario (nombre,email,contraseña) values ("Erik","erik@gmail.com","erik1234");
insert into usuario (nombre,email,contraseña) values ("Claudia","claudia@gmail.com","claudia1234");
insert into usuario (nombre,email,contraseña) values ("Mar","mar@gmail.com","mar1234");
insert into usuario (nombre,email,contraseña) values ("Rosa","rosa@gmail.com","rosa1234");
insert into usuario (nombre,email,contraseña) values ("Marc","marc@gmail.com","marc1234");
insert into usuario (nombre,email,contraseña) values ("Lex","lex@gmail.com","lex1234");
insert into usuario (nombre,email,contraseña) values ("Gerrau","gerrau@gmail.com","gerrau1234");
insert into usuario (nombre,email,contraseña) values ("Abel","abel@gmail.com","abel1234");
insert into usuario (nombre,email,contraseña) values ("Mateo","mateo@gmail.com","mateo1234");
insert into usuario (nombre,email,contraseña) values ("Daniel","daniel@gmail.com","daniel1234");
insert into usuario (nombre,email,contraseña) values ("Marcos","marcos@gmail.com","marcos1234");
insert into usuario (nombre,email,contraseña) values ("Nicolás","nicolas@gmail.com","nicolas1234");
insert into usuario (nombre,email,contraseña) values ("Lara","lara@gmail.com","lara1234");
insert into usuario (nombre,email,contraseña) values ("Marta","marta@gmail.com","marta1234");
insert into usuario (nombre,email,contraseña) values ("Emma","emma@gmail.com","emma1234");
insert into usuario (nombre,email,contraseña) values ("Paula","paula@gmail.com","paula1234");
insert into usuario (nombre,email,contraseña) values ("Martina","martina@gmail.com","martina1234");


insert into receta (tiempo_preparacion,usuario_id,descripcion,instrucciones,nombre) values (5400,1,"Sabrosa pizza casera","Hacer la masa, reposar, echar ingredientes desados, calentar","Pizza");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2400, 3, "Deliciosa pasta al pesto", "Cocinar la pasta al dente, mezclar con salsa pesto casera, servir caliente.", "Pasta al Pesto");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3000, 5, "Sabroso ramen de pollo", "Cocinar los fideos ramen, preparar caldo de pollo, añadir pollo cocido, huevo, cebolla verde y servir caliente.", "Ramen de Pollo");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3600, 8, "Lasaña vegetariana con ricotta y espinacas", "Preparar capas de pasta, salsa de tomate, ricotta, espinacas, mozzarella y parmesano, hornear hasta que esté dorado.", "Lasaña Vegetariana");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (1800, 12, "Parrillada de verduras mediterráneas", "Cortar verduras frescas (pimientos, calabacines, berenjenas, champiñones), marinar con aceite de oliva, ajo y hierbas, asar a la parrilla hasta que estén tiernas.", "Parrillada de Verduras");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2700, 7, "Rolls de sushi de salmón fresco", "Cocinar arroz de sushi, extender en hojas de alga nori, añadir tiras de salmón crudo, aguacate, pepino, enrollar y cortar en piezas, servir con salsa de soja y wasabi.", "Sushi de Salmón");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (1200, 19, "Clásica ensalada César con pollo a la parrilla", "Preparar lechuga romana, pollo a la parrilla, picatostes, queso parmesano y aderezo César, mezclar y servir.", "Ensalada César");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2400, 4, "Tacos mexicanos al pastor", "Marinar carne de cerdo con adobo de achiote y especias, asar en trompo, cortar en tiras, servir en tortillas de maíz con cebolla, piña, cilantro y salsa de tomate.", "Tacos al Pastor");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2700, 11, "Sabroso curry de verduras", "Saltear cebolla, pimientos, zanahorias, calabacines y patatas en pasta de curry, agregar leche de coco y cocinar a fuego lento hasta que las verduras estén tiernas, servir con arroz blanco.", "Curry de Verduras");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2400, 9, "Risotto cremoso de champiñones", "Saltear arroz arborio en mantequilla, agregar caldo de verduras caliente gradualmente, añadir champiñones salteados, queso parmesano y perejil fresco, remover hasta obtener una consistencia cremosa.", "Risotto de Champiñones");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3600, 17, "Pollo jugoso al horno con patatas crujientes", "Marinar muslos de pollo con hierbas y limón, colocar en una bandeja para hornear junto con patatas cortadas en trozos, hornear hasta que estén dorados y cocidos.", "Pollo al Horno con Patatas");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2700, 6, "Enchiladas de pollo con salsa roja", "Cocinar pechugas de pollo, desmenuzar y rellenar tortillas de maíz, cubrir con salsa roja de chiles secos, queso y crema, hornear hasta que el queso se derrita.", "Enchiladas de Pollo");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3600, 14, "Paella valenciana con mariscos frescos", "Sofreír cebolla, ajo y pimientos, agregar arroz bomba y caldo de pescado, añadir mariscos (calamares, gambas, mejillones), cocinar hasta que el arroz esté tierno y se forme una costra en la parte inferior.", "Paella de Mariscos");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2400, 2, "Postre italiano cremoso de café y mascarpone", "Batir yemas de huevo con azúcar, agregar mascarpone y licor de café, remojar bizcochos en café, alternar capas de bizcocho y crema, refrigerar y espolvorear con cacao en polvo antes de servir.", "Tiramisú");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (1800, 16, "Refrescante ceviche de pescado con leche de tigre", "Marinar pescado blanco fresco en jugo de limón, agregar cebolla roja, cilantro, ají, maíz y camote, servir frío con lechuga y cancha tostada.", "Ceviche Peruano");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3600, 10, "Plato griego tradicional de berenjenas y carne", "Cocinar berenjenas en rodajas, hacer una salsa de carne de cordero, intercalar capas de berenjena y salsa en una bandeja, cubrir con bechamel y hornear hasta que esté dorado y burbujeante.", "Moussaka Griega");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2700, 18, "Sopa reconfortante de lentejas con verduras", "Cocinar cebolla, zanahorias, apio y lentejas en caldo de verduras, condimentar con comino, pimentón y tomillo, cocinar a fuego lento hasta que las lentejas estén tiernas.", "Sopa de Lentejas");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (1800, 13, "Wraps frescos de pollo a la parrilla y aguacate", "Asar pechugas de pollo, cortar en tiras, armar wraps con tortillas de trigo, pollo, aguacate, lechuga, tomate y aderezo ranch, enrollar y servir.", "Wraps de Pollo y Aguacate");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2400, 1, "Deliciosos gnocchi caseros con salsa de tomate fresco y albahaca", "Cocinar gnocchi caseros en agua hirviendo, hacer una salsa de tomate con tomates frescos, ajo y albahaca, servir los gnocchi con la salsa y queso parmesano rallado.", "Gnocchi con Salsa de Tomate y Albahaca");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3600, 15, "Estofado de carne de res y verduras al estilo irlandés", "Dorar carne de res en una olla grande, agregar cebolla, zanahorias, apio y patatas, cubrir con caldo de carne, cocinar a fuego lento hasta que la carne esté tierna y las verduras estén cocidas, servir caliente.", "Estofado Irlandés");


insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 3, 5, "¡Me encantó este ramen! Perfecto para un día frío.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 6, 7, "El sushi estaba fresco y delicioso. Definitivamente volveré por más.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 10, 9, "El curry de verduras fue una sorpresa increíble. ¡Tan reconfortante!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 13, 11, "Las enchiladas de pollo son mi plato mexicano favorito. ¡Estaban deliciosas!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 16, 13, "La paella estaba llena de mariscos frescos. ¡Una auténtica delicia!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 19, 15, "El estofado irlandés me recordó a las comidas caseras de mi abuela. ¡Tan reconfortante!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 2, 17, "La pasta al pesto estaba bien, pero le faltaba un toque de ajo.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 5, 19, "La parrillada de verduras mediterráneas fue una opción perfecta para una cena ligera y saludable.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 8, 2, "¡La lasaña vegetariana estaba tan cremosa y deliciosa!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 11, 4, "Los tacos al pastor tenían un sabor auténtico mexicano. ¡Me encantaron!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 14, 6, "El tiramisú estaba demasiado empapado de café para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 17, 8, "El ceviche peruano fue una explosión de sabores frescos. ¡Una delicia!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 20, 10, "El gnocchi con salsa de tomate y albahaca era como una fiesta en mi boca. ¡Increíble!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 23, 12, "El pollo al horno con patatas crujientes era tan jugoso y sabroso. ¡Una cena perfecta!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 4, 14, "La ensalada César fue una opción ligera pero satisfactoria para el almuerzo.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 7, 16, "Los tacos al pastor estaban bien, pero la carne estaba un poco seca.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 9, 18, "El curry de verduras tenía justo el nivel adecuado de especias. ¡Delicioso!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 12, 1, "El risotto de champiñones era cremoso y lleno de sabor. ¡Me encantó!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 15, 3, "La moussaka griega era una explosión de sabor. ¡Increíblemente sabrosa!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 18, 5, "La sopa de lentejas fue reconfortante en un día frío. ¡Perfecta para calentar el alma!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 21, 7, "Los wraps de pollo y aguacate estaban frescos y llenos de sabor. ¡Un almuerzo perfecto!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 24, 9, "El estofado irlandés era abundante y delicioso. ¡Me recordó a casa!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 1, 11, "La pizza estaba bien, pero preferiría una cobertura más variada.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 14, 13, "La paella de mariscos me transportó directamente a la costa española. ¡Deliciosa!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 17, 15, "El tiramisú estaba delicioso, pero un poco demasiado dulce para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 20, 17, "Los gnocchi con salsa de tomate y albahaca eran tan reconfortantes. ¡Perfectos para una cena de domingo!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 23, 19, "El pollo al horno con patatas crujientes era una opción reconfortante para la cena. ¡Me encantó!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 3, 2, "El ramen de pollo estaba bien, pero me hubiera gustado más caldo.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 6, 4, "El sushi de salmón era fresco y delicioso. ¡Lo mejor que he probado!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 9, 6, "El curry de verduras estaba sabroso, pero un poco picante para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 12, 8, "El risotto de champiñones era cremoso y lleno de sabor. ¡Una delicia!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 15, 10, "La moussaka griega estaba bien, pero me hubiera gustado más carne.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 18, 12, "La sopa de lentejas fue reconfortante y deliciosa. ¡Perfecta para un día frío!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 21, 14, "Los wraps de pollo y aguacate eran frescos y sabrosos. ¡Los amé!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 24, 16, "El estofado irlandés era abundante y lleno de sabor. ¡Perfecto para una cena familiar!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 2, 18, "La pasta al pesto estaba bien, pero le faltaba algo de sabor.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 5, 1, "La parrillada de verduras mediterráneas era fresca y deliciosa. ¡Perfecta para el verano!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 8, 3, "La lasaña vegetariana estaba cremosa y sabrosa. ¡La mejor que he probado!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 11, 5, "Los tacos al pastor eran auténticos y sabrosos. ¡Me transportaron a México!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 14, 7, "La paella de mariscos estaba bien, pero me hubiera gustado más azafrán.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 17, 9, "La sopa de lentejas era reconfortante y deliciosa. ¡Perfecta para una comida rápida!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 20, 11, "Los gnocchi con salsa de tomate y albahaca eran cremosos y deliciosos. ¡Un verdadero placer!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 23, 13, "El pollo al horno con patatas crujientes era una delicia. ¡La salsa de limón le daba un toque único!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (3, 1, 15, "La pizza estaba bien, pero la base estaba un poco blanda para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 4, 17, "La ensalada César era fresca y sabrosa. ¡Perfecta para un almuerzo ligero!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 7, 19, "El sushi de salmón estaba fresco y delicioso. ¡Lo recomendaría!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 10, 2, "El curry de verduras era tan reconfortante y delicioso. ¡Lo volveré a hacer!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 13, 4, "Las enchiladas de pollo estaban sabrosas pero un poco picantes para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 16, 6, "La paella de mariscos era auténtica y deliciosa. ¡Me recordó a mis vacaciones en España!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 19, 8, "La sopa de lentejas era sabrosa y reconfortante. ¡Perfecta para un día frío!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 22, 10, "Los wraps de pollo y aguacate eran frescos y deliciosos. ¡Los volveré a hacer!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 25, 12, "El estofado irlandés era sabroso pero un poco pesado para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 3, 1, "La pasta al pesto era deliciosa y fácil de hacer. ¡La recomendaría!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 6, 3, "El sushi de salmón era fresco y sabroso. ¡Me encantó!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 9, 5, "El curry de verduras era perfectamente sazonado y lleno de sabor. ¡Definitivamente lo haré de nuevo!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 12, 7, "El risotto de champiñones era cremoso y delicioso. ¡Una gran receta!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 15, 9, "La moussaka griega era tan reconfortante y deliciosa. ¡Una nueva receta favorita!");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (4, 18, 11, "La sopa de lentejas era sabrosa pero un poco espesa para mi gusto.");
insert into valoracion (puntuacion, receta_id, usuario_id, comentario) values (5, 21, 13, "Los wraps de pollo y aguacate eran frescos y deliciosos. ¡Perfectos para un almuerzo rápido!");


insert into categoria (nombre) values ("Italiana");
insert into categoria (nombre) values ("Mexicana");
insert into categoria (nombre) values ("Japonesa");
insert into categoria (nombre) values ("Mediterránea");
insert into categoria (nombre) values ("Vegetariana");
insert into categoria (nombre) values ("Asiática");
insert into categoria (nombre) values ("Americana");
insert into categoria (nombre) values ("Árabe");
insert into categoria (nombre) values ("Griega");
insert into categoria (nombre) values ("India");
insert into categoria (nombre) values ("Francesa");
insert into categoria (nombre) values ("Española");
insert into categoria (nombre) values ("Tailandesa");
insert into categoria (nombre) values ("Peruana");
insert into categoria (nombre) values ("China");
insert into categoria (nombre) values ("Brasileña");
insert into categoria (nombre) values ("Coreana");
insert into categoria (nombre) values ("Caribeña");
insert into categoria (nombre) values ("Sudafricana");

insert into receta_categoria (categoria_id, receta_id) values (2, 1);
insert into receta_categoria (categoria_id, receta_id) values (10, 1);
insert into receta_categoria (categoria_id, receta_id) values (2, 2);
insert into receta_categoria (categoria_id, receta_id) values (12, 2);
insert into receta_categoria (categoria_id, receta_id) values (3, 3);
insert into receta_categoria (categoria_id, receta_id) values (5, 3);
insert into receta_categoria (categoria_id, receta_id) values (4, 4);
insert into receta_categoria (categoria_id, receta_id) values (14, 4);
insert into receta_categoria (categoria_id, receta_id) values (5, 5);
insert into receta_categoria (categoria_id, receta_id) values (13, 5);
insert into receta_categoria (categoria_id, receta_id) values (4, 6);
insert into receta_categoria (categoria_id, receta_id) values (17, 6);
insert into receta_categoria (categoria_id, receta_id) values (6, 7);
insert into receta_categoria (categoria_id, receta_id) values (11, 7);
insert into receta_categoria (categoria_id, receta_id) values (2, 8);
insert into receta_categoria (categoria_id, receta_id) values (9, 8);
insert into receta_categoria (categoria_id, receta_id) values (3, 9);
insert into receta_categoria (categoria_id, receta_id) values (10, 9);
insert into receta_categoria (categoria_id, receta_id) values (8, 10);
insert into receta_categoria (categoria_id, receta_id) values (15, 10);
insert into receta_categoria (categoria_id, receta_id) values (1, 11);
insert into receta_categoria (categoria_id, receta_id) values (18, 11);
insert into receta_categoria (categoria_id, receta_id) values (13, 12);
insert into receta_categoria (categoria_id, receta_id) values (16, 12);
insert into receta_categoria (categoria_id, receta_id) values (6, 13);
insert into receta_categoria (categoria_id, receta_id) values (14, 13);
insert into receta_categoria (categoria_id, receta_id) values (2, 14);
insert into receta_categoria (categoria_id, receta_id) values (7, 14);
insert into receta_categoria (categoria_id, receta_id) values (9, 15);
insert into receta_categoria (categoria_id, receta_id) values (12, 15);
insert into receta_categoria (categoria_id, receta_id) values (11, 16);
insert into receta_categoria (categoria_id, receta_id) values (17, 16);
insert into receta_categoria (categoria_id, receta_id) values (3, 17);
insert into receta_categoria (categoria_id, receta_id) values (6, 17);
insert into receta_categoria (categoria_id, receta_id) values (5, 18);
insert into receta_categoria (categoria_id, receta_id) values (7, 18);
insert into receta_categoria (categoria_id, receta_id) values (1, 19);
insert into receta_categoria (categoria_id, receta_id) values (9, 19);
insert into receta_categoria (categoria_id, receta_id) values (14, 20);
insert into receta_categoria (categoria_id, receta_id) values (15, 20);

insert into ingrediente (nombre) values ("Harina");
insert into ingrediente (nombre) values ("Levadura");
insert into ingrediente (nombre) values ("Sal");
insert into ingrediente (nombre) values ("Aceite de oliva");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Albahaca");
insert into ingrediente (nombre) values ("Queso mozzarella");
insert into ingrediente (nombre) values ("Pasta");
insert into ingrediente (nombre) values ("Pesto");
insert into ingrediente (nombre) values ("Pollo");
insert into ingrediente (nombre) values ("Fideos ramen");
insert into ingrediente (nombre) values ("Caldo de pollo");
insert into ingrediente (nombre) values ("Huevo");
insert into ingrediente (nombre) values ("Cebolla verde");
insert into ingrediente (nombre) values ("Ricotta");
insert into ingrediente (nombre) values ("Espinacas");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Mantequilla");
insert into ingrediente (nombre) values ("Champiñones");
insert into ingrediente (nombre) values ("Pollo");
insert into ingrediente (nombre) values ("Patatas");
insert into ingrediente (nombre) values ("Salmón");
insert into ingrediente (nombre) values ("Arroz de sushi");
insert into ingrediente (nombre) values ("Alga nori");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Pepino");
insert into ingrediente (nombre) values ("Salsa de soja");
insert into ingrediente (nombre) values ("Wasabi");
insert into ingrediente (nombre) values ("Lechuga romana");
insert into ingrediente (nombre) values ("Picatostes");
insert into ingrediente (nombre) values ("Ajo");
insert into ingrediente (nombre) values ("Cerdo");
insert into ingrediente (nombre) values ("Achiote");
insert into ingrediente (nombre) values ("Piña");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Curry");
insert into ingrediente (nombre) values ("Leche de coco");
insert into ingrediente (nombre) values ("Arroz arborio");
insert into ingrediente (nombre) values ("Queso mascarpone");
insert into ingrediente (nombre) values ("Café");
insert into ingrediente (nombre) values ("Huevos");
insert into ingrediente (nombre) values ("Bizcochos");
insert into ingrediente (nombre) values ("Cacao en polvo");
insert into ingrediente (nombre) values ("Pescado blanco");
insert into ingrediente (nombre) values ("Jugo de limón");
insert into ingrediente (nombre) values ("Cebolla roja");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Ají");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Camote");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Patatas");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Comino");
insert into ingrediente (nombre) values ("Pimentón");
insert into ingrediente (nombre) values ("Tomillo");
insert into ingrediente (nombre) values ("Pechugas de pollo");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Lechuga");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Salsa ranch");
insert into ingrediente (nombre) values ("Gnocchi");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Zanahorias");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Champiñones");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Limón");
insert into ingrediente (nombre) values ("Pescado blanco");
insert into ingrediente (nombre) values ("Arroz bomba");
insert into ingrediente (nombre) values ("Mariscos");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Bechamel");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Queso mozzarella");
insert into ingrediente (nombre) values ("Queso cheddar");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Chile seco");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Crema");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Albóndigas");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Pasta");
insert into ingrediente (nombre) values ("Queso gorgonzola");
insert into ingrediente (nombre) values ("Harina");
insert into ingrediente (nombre) values ("Carne molida");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Queso feta");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Pollo");
insert into ingrediente (nombre) values ("Huevos");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Limón");
insert into ingrediente (nombre) values ("Jugo de limón");
insert into ingrediente (nombre) values ("Cebolla morada");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Lechuga");
insert into ingrediente (nombre) values ("Cancha");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Carne de cerdo");
insert into ingrediente (nombre) values ("Achiote");
insert into ingrediente (nombre) values ("Piña");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Zanahorias");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Patatas");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Bechamel");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Comino");
insert into ingrediente (nombre) values ("Pimentón");
insert into ingrediente (nombre) values ("Tomillo");
insert into ingrediente (nombre) values ("Pechugas de pollo");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Lechuga");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Salsa ranch");
insert into ingrediente (nombre) values ("Gnocchi");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Zanahorias");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Champiñones");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Limón");
insert into ingrediente (nombre) values ("Pescado blanco");
insert into ingrediente (nombre) values ("Arroz bomba");
insert into ingrediente (nombre) values ("Mariscos");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Bechamel");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Queso mozzarella");
insert into ingrediente (nombre) values ("Queso cheddar");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Chile seco");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Crema");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Albóndigas");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Pasta");
insert into ingrediente (nombre) values ("Queso gorgonzola");
insert into ingrediente (nombre) values ("Harina");
insert into ingrediente (nombre) values ("Carne molida");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Queso feta");
insert into ingrediente (nombre) values ("Aguacate");

insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (400, 1, 1, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 3, 1, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 18, 1, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 19, 1, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 20, 1, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 21, 1, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 28, 2, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 29, 2, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 30, 2, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 31, 2, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 32, 2, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 33, 2, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 34, 3, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 35, 3, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 36, 3, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 37, 3, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 38, 3, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 44, 4, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 45, 4, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 20, 4, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 4, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 32, 4, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 45, 5, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 20, 5, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 5, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 48, 5, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 49, 5, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 50, 5, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 34, 6, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 35, 6, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 36, 6, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 37, 6, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 38, 6, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 57, 7, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 58, 7, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 59, 7, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 60, 7, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 49, 7, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 50, 7, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 61, 8, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 62, 8, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 20, 8, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 21, 8, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 32, 8, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 45, 9, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 20, 9, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 9, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 48, 9, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 49, 9, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 50, 9, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 45, 10, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 20, 10, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 10, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 64, 10, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 65, 10, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 66, 10, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 61, 11, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 62, 11, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 59, 11, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 60, 11, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 67, 11, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 68, 11, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 62, 12, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 59, 12, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 60, 12, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 69, 12, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 68, 12, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 70, 12, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 45, 13, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 20, 13, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 13, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 49, 13, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 50, 13, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 71, 13, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 45, 14, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 59, 14, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 60, 14, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 67, 14, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 68, 14, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 70, 14, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 45, 15, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 20, 15, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 15, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 48, 15, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 49, 15, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 50, 15, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 45, 16, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 20, 16, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 21, 16, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 67, 16, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 68, 16, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 72, 16, "unidad");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (300, 62, 17, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (200, 73, 17, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 59, 17, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (100, 60, 17, "g");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (50, 74, 17, "ml");
insert into receta_ingrediente (cantidad, ingrediente_id, receta_id, unidades) values (1, 68, 17, "unidad");

