insert into user (username,password,rol) values ("admin","admin",'ADMIN');
"insert into user (username,password,rol) values ("invitado","invitado",'INVITADO');"



insert into receta (tiempo_preparacion,usuario_id,descripcion,instrucciones,nombre) values (5400,1,"Sabrosa pizza casera","Hacer la masa, reposar, echar ingredientes desados, calentar","Pizza");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (2400, 2, "Deliciosa pasta al pesto", "Cocinar la pasta al dente, mezclar con salsa pesto casera, servir caliente.", "Pasta al Pesto");
insert into receta (tiempo_preparacion, usuario_id, descripcion, instrucciones, nombre) values (3000, 1, "Sabroso ramen de pollo", "Cocinar los fideos ramen, preparar caldo de pollo, añadir pollo cocido, huevo, cebolla verde y servir caliente.", "Ramen de Pollo");


insert into categoria (nombre) values ("Entrantes");
insert into categoria (nombre) values ("Postres");
insert into categoria (nombre) values ("Batidos");
insert into categoria (nombre) values ("Italiana");
insert into categoria (nombre) values ("Mexicana");
insert into categoria (nombre) values ("Asiática");
insert into categoria (nombre) values ("Vegetariana");
insert into categoria (nombre) values ("Vegana");
insert into categoria (nombre) values ("Cumpleaños");
insert into categoria (nombre) values ("Rápidas");
insert into categoria (nombre) values ("Pocos ingredientes");
insert into categoria (nombre) values ("Española");
insert into categoria (nombre) values ("Arroces");
insert into categoria (nombre) values ("Carnes");
insert into categoria (nombre) values ("Peruana");
insert into categoria (nombre) values ("Hamburguesas");
insert into categoria (nombre) values ("Ecuatoriana");
insert into categoria (nombre) values ("Pizzas");
insert into categoria (nombre) values ("Pastas");


insert into ingrediente (nombre) values ("Harina");
insert into ingrediente (nombre) values ("Levadura");
insert into ingrediente (nombre) values ("Sal");
insert into ingrediente (nombre) values ("Aceite de oliva");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Albahaca");
insert into ingrediente (nombre) values ("Queso mozzarella");
insert into ingrediente (nombre) values ("Pasta");
insert into ingrediente (nombre) values ("Pesto");
insert into ingrediente (nombre) values ("Pollo");
insert into ingrediente (nombre) values ("Fideos ramen");
insert into ingrediente (nombre) values ("Caldo de pollo");
insert into ingrediente (nombre) values ("Huevo");
insert into ingrediente (nombre) values ("Cebolla verde");
insert into ingrediente (nombre) values ("Ricotta");
insert into ingrediente (nombre) values ("Espinacas");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Mantequilla");
insert into ingrediente (nombre) values ("Champiñones");
insert into ingrediente (nombre) values ("Pollo");
insert into ingrediente (nombre) values ("Patatas");
insert into ingrediente (nombre) values ("Salmón");
insert into ingrediente (nombre) values ("Arroz de sushi");
insert into ingrediente (nombre) values ("Alga nori");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Pepino");
insert into ingrediente (nombre) values ("Salsa de soja");
insert into ingrediente (nombre) values ("Wasabi");
insert into ingrediente (nombre) values ("Lechuga romana");
insert into ingrediente (nombre) values ("Picatostes");
insert into ingrediente (nombre) values ("Ajo");
insert into ingrediente (nombre) values ("Cerdo");
insert into ingrediente (nombre) values ("Achiote");
insert into ingrediente (nombre) values ("Piña");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Curry");
insert into ingrediente (nombre) values ("Leche de coco");
insert into ingrediente (nombre) values ("Arroz arborio");
insert into ingrediente (nombre) values ("Queso mascarpone");
insert into ingrediente (nombre) values ("Café");
insert into ingrediente (nombre) values ("Huevos");
insert into ingrediente (nombre) values ("Bizcochos");
insert into ingrediente (nombre) values ("Cacao en polvo");
insert into ingrediente (nombre) values ("Pescado blanco");
insert into ingrediente (nombre) values ("Jugo de limón");
insert into ingrediente (nombre) values ("Cebolla roja");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Ají");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Camote");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Patatas");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Comino");
insert into ingrediente (nombre) values ("Pimentón");
insert into ingrediente (nombre) values ("Tomillo");
insert into ingrediente (nombre) values ("Pechugas de pollo");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Lechuga");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Salsa ranch");
insert into ingrediente (nombre) values ("Gnocchi");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Zanahorias");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Champiñones");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Limón");
insert into ingrediente (nombre) values ("Pescado blanco");
insert into ingrediente (nombre) values ("Arroz bomba");
insert into ingrediente (nombre) values ("Mariscos");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Bechamel");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Queso mozzarella");
insert into ingrediente (nombre) values ("Queso cheddar");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Chile seco");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Crema");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Albóndigas");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Pasta");
insert into ingrediente (nombre) values ("Queso gorgonzola");
insert into ingrediente (nombre) values ("Harina");
insert into ingrediente (nombre) values ("Carne molida");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Queso feta");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Pollo");
insert into ingrediente (nombre) values ("Huevos");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Limón");
insert into ingrediente (nombre) values ("Jugo de limón");
insert into ingrediente (nombre) values ("Cebolla morada");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Lechuga");
insert into ingrediente (nombre) values ("Cancha");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Carne de cerdo");
insert into ingrediente (nombre) values ("Achiote");
insert into ingrediente (nombre) values ("Piña");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Zanahorias");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Patatas");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Bechamel");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Comino");
insert into ingrediente (nombre) values ("Pimentón");
insert into ingrediente (nombre) values ("Tomillo");
insert into ingrediente (nombre) values ("Pechugas de pollo");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Aguacate");
insert into ingrediente (nombre) values ("Lechuga");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Salsa ranch");
insert into ingrediente (nombre) values ("Gnocchi");
insert into ingrediente (nombre) values ("Queso parmesano");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Zanahorias");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Caldo de carne");
insert into ingrediente (nombre) values ("Berenjenas");
insert into ingrediente (nombre) values ("Lentejas");
insert into ingrediente (nombre) values ("Cebolla");
insert into ingrediente (nombre) values ("Apio");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Champiñones");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Limón");
insert into ingrediente (nombre) values ("Pescado blanco");
insert into ingrediente (nombre) values ("Arroz bomba");
insert into ingrediente (nombre) values ("Mariscos");
insert into ingrediente (nombre) values ("Carne de cordero");
insert into ingrediente (nombre) values ("Bechamel");
insert into ingrediente (nombre) values ("Tortillas de trigo");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Queso mozzarella");
insert into ingrediente (nombre) values ("Queso cheddar");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Maíz");
insert into ingrediente (nombre) values ("Pimientos");
insert into ingrediente (nombre) values ("Tortillas de maíz");
insert into ingrediente (nombre) values ("Chile seco");
insert into ingrediente (nombre) values ("Cilantro");
insert into ingrediente (nombre) values ("Crema");
insert into ingrediente (nombre) values ("Arroz");
insert into ingrediente (nombre) values ("Albóndigas");
insert into ingrediente (nombre) values ("Carne de res");
insert into ingrediente (nombre) values ("Pasta");
insert into ingrediente (nombre) values ("Queso gorgonzola");
insert into ingrediente (nombre) values ("Harina");
insert into ingrediente (nombre) values ("Carne molida");
insert into ingrediente (nombre) values ("Tomate");
insert into ingrediente (nombre) values ("Queso feta");
insert into ingrediente (nombre) values ("Aguacate");
